# Site settings
title: Computational Science Alliance
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://csa.ru" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

sass:
  style: :compressed

#  bibliography_list_tag: "table"
#  bibliography_item_tag: "tr"
#  details_link: "[more]"
#  bibliography: books.bib

scholar:
  style: gost-r-7-0-5-2008-no-citation-number
  sort_by: "year"
  order: descending
  bibtex_options:
    strip: false

