# Site settings
title: Computational Science Alliance
description: >
  Computational Science Alliance (CSA) создан в 2004 г. на базе Института высокопроизводительных вычислений и Информационных Систем, который в свое время был преобразован из Института Высокопроизводительных Вычислений и Баз Данных, являвшегося российским лидером в инновации современных информационных технологий на основе высокопроизводительной компьютерной техники, Учебно-научного центра по вычислительной механике Института Теплофизики Экстремальных Состояний РАН Санкт-Петербургского политехнического университета и кафедры высокопроизводительных вычислений СПбГПУ. Деятельность направлена на развитие новых технологий в использовании суперкомпьютеров в различных областях науки и техники, осуществление информационной и вычислительной поддержки государственных учреждений, исследовательских и образовательных организаций.
url: http://csa.ru
encoding: utf-8
markdown: kramdown
highlighter: pygments

# multilingual pages
languages: ["ru", "en"]
exclude_from_localizations: ["analitik", "children", "bin", "raw-papers"]

exclude: ["bin", "Gemfile", "Gemfile.lock", "TODO", "gost.csl", "Makefile", "raw-papers"]

# compress and cache JS and CSS files preserving copyright
assets:
  js_compressor: uglifier_with_copyright
  css_compressor: sass
  gzip: false
  cache: true

# compress HTML files
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

# BibTeX support
scholar:
  style: gost
  sort_by: "year"
  order: descending
  repository: repository
  locale: en
  bibliography: ["books.bib", "papers.bib", "theses.bib", "grants.bib"]
  details_dir: bib
  details_layout: details.html
  details_link: "[more]"
  bibtex_skip_fields: [rawentry, annote]
  bibtex_options:
    strip: false
